# config.yml
# 主配置文件
dupe:
  # 是否启用/dupe复制命令
  enable: true
  # 复制冷却时间（秒）
  cooldown: 20

shulker_dupe:
  # 是否启用潜影盒复制功能
  enable: true
  # 需要挖掘多少个潜影盒才会触发复制
  break: 10
  
# 禁止使用的命令列表
# 所有玩家（包括OP）将无法使用这些命令，但控制台仍可使用
ban-command:
  - ban-ip
  - ban
  - op
  - deop
  - kill
  - stop
  - restart
  - whitelist
