# 主配置文件
dupe:
  enable: true
  cooldown: 20

shulker_dupe:
  enable: true
  break: 10
  
# 禁止使用的命令列表
ban-command:
  - ban-ip
  - ban
  - op

# 反卡服配置
anti-lag:
  enable: true
  check-interval: 600
  tps-threshold: 15.0
  clear-dropped-items: true
  clear-mobs: true
  clear-chunk-entities: true
  entity-age-threshold: 12000
  mob-age-threshold: 6000
  broadcast-cleanup: true

# 高频红石限制配置
redstone:
  enable: true
  min-interval: 100
  warn-player: true
  record-expire: 60000

# 鞘翅平飞限制配置
elytra:
  enable: false
  vertical-threshold: 0.05
  bounce-strength: 0.5
  bounce-cooldown: 1000
  warn-player: true

# 日志配置
logging:
  # 插件启动时显示LOGO
  startup-logo: true
  # 物品复制日志
  dupe: true
  # 潜影盒复制日志
  shulker-dupe: true
  # 潜影盒进度日志
  shulker-progress: true
  # 潜影盒重置日志
  shulker-reset: true
  # 命令禁用日志
  command-block: true
  # 高频红石阻止日志
  redstone-block: true
  # 鞘翅平飞回弹日志
  elytra-bounce: true
  # 自动清理日志
  lagclean: true
  # 手动清理日志
  lagclean-manual: true
  # 插件重载日志
  reload: true
