# AnarchyCore 配置文件
# 版本: 1.0
# 作者: Traveler114514

# 物品复制配置
dupe:
  # 是否启用物品复制功能
  enable: true
  # 复制命令冷却时间（秒）
  cooldown: 20

# 潜影盒复制配置
shulker_dupe:
  # 是否启用潜影盒复制功能
  enable: true
  # 需要挖掘多少个潜影盒才会触发复制
  break: 10
  
# 禁止使用的命令列表
# 所有玩家（包括OP）将无法使用这些命令
ban-command:
  - ban-ip
  - ban
  - op

# 反卡服配置
anti-lag:
  # 是否启用反卡服功能
  enable: true
  # 检查间隔（tick）
  check-interval: 600
  # TPS阈值，低于此值触发清理
  tps-threshold: 15.0
  # 是否清理掉落物
  clear-dropped-items: true
  # 是否清理怪物
  clear-mobs: true
  # 是否清理区块实体
  clear-chunk-entities: true
  # 实体存在时间阈值（tick）
  entity-age-threshold: 12000
  # 怪物存在时间阈值（tick）
  mob-age-threshold: 6000
  # 是否广播清理信息
  broadcast-cleanup: true

# 高频红石限制配置
redstone:
  # 是否启用高频红石限制
  enable: true
  # 最小激活间隔（毫秒），低于此值视为高频
  min-interval: 100
  # 是否向附近玩家发送警告
  warn-player: true
  # 红石记录过期时间（毫秒）
  record-expire: 60000

# 鞘翅平飞限制配置
elytra:
  # 是否启用鞘翅平飞限制（默认关闭）
  enable: false
  # 垂直速度阈值（绝对值小于此值视为平飞）
  vertical-threshold: 0.05
  # 回弹力度（向上速度）
  bounce-strength: 0.5
  # 回弹冷却时间（毫秒）
  bounce-cooldown: 1000
  # 是否向玩家发送警告消息
  warn-player: true

# 日志配置
logging:
  # 插件启动时显示LOGO
  startup-logo: true
  # 物品复制日志
  dupe: true
  # 潜影盒复制日志
  shulker-dupe: true
  # 潜影盒进度日志
  shulker-progress: true
  # 潜影盒重置日志
  shulker-reset: true
  # 命令禁用日志
  command-block: true
  # 高频红石阻止日志
  redstone-block: true
  # 鞘翅平飞回弹日志
  elytra-bounce: true
  # 自动清理日志
  lagclean: true
  # 手动清理日志
  lagclean-manual: true
  # 插件重载日志
  reload: true
